services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use dynamic image from Jenkins pipeline or fallback to build
    image: ${HEALTHCONNECT_IMAGE:-healthconnect-app:latest}
    container_name: healthconnect-app-${BUILD_NUMBER:-local}
    ports:
      - "${APP_PORT:-3017}:3000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - MONGO_URI=mongodb://${MONGO_USER:-healthconnect}:${MONGO_PASSWORD:-healthconnect123}@mongo:${MONGO_PORT:-27017}/${MONGO_DB:-healthconnect}?authSource=admin
      - EMAIL_SERVICE=${EMAIL_SERVICE:-gmail}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - JWT_SECRET=${JWT_SECRET:-healthconnect-jwt-secret-2025}
      - SESSION_SECRET=${SESSION_SECRET:-healthconnect-session-secret-2025}
      # Jenkins build information
      - BUILD_NUMBER=${BUILD_NUMBER:-local}
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - JENKINS_BUILD_URL=${BUILD_URL}
    restart: unless-stopped
    networks:
      - healthconnect-network
    volumes:
      - ./logs:/app/logs
      - ./public/uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "|", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.healthconnect.service=app"
      - "com.healthconnect.version=${APP_VERSION:-1.0.0}"
      - "com.healthconnect.build=${BUILD_NUMBER:-local}"

  mongo:
    image: mongo:7
    container_name: healthconnect-mongo
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - healthconnect-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
    driver: local

networks:
  healthconnect-network:
    driver: bridge
