---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: healthconnect
  labels:
    app: mongodb
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: healthconnect
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: mongodb
        image: mongo:7
        command: ["mongod", "--config", "/etc/mongod.conf"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: healthconnect
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: conf
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            cpu: "150m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command: ["mongosh", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mongosh", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: data
        hostPath:
          path: /mnt/data/mongodb
          type: DirectoryOrCreate
      - name: conf
        configMap:
          name: mongodb-config

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: healthconnect
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
