---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: healthconnect
  labels:
    app: mongodb
    component: database
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: healthconnect
  labels:
    app: mongodb
    component: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
      component: database
  template:
    metadata:
      labels:
        app: mongodb
        component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: healthconnect
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config-volume
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        command: ["mongod", "--config", "/etc/mongod.conf"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: mongodb-data
        hostPath:
          path: /mnt/data/mongodb   # host node path
          type: DirectoryOrCreate   # creates folder if it doesn’t exist
      - name: mongodb-config-volume
        configMap:
          name: mongodb-config
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: healthconnect
spec:
  type: ClusterIP
  selector:
    app: mongodb
    component: database
  ports:
  - port: 27017
    targetPort: 27017
